apiVersion: apps/v1
kind: Deployment
metadata: 
  name: depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: debate
  template:
    metadata:
      labels:
        app: debate
    spec:
      containers:
        - name: debate
          image: testardr/debate
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec: 
  selector: 
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec: 
  selector: 
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000